Update README example to the latest commit
The example commit is so old, it dates back to when this repo was called
codechecker_bazel, which actually results in an error:
```
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> rules_codechecker@_: the MODULE.bazel file of rules_codechecker@_ declares a different name (bazel_codechecker)
```